config/routes.rb
Rails.application.routes.draw do

  root 'pages#learn'
  resources :pledges
  resources :charities

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :pledge, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def new
    @pledge = Pledge.new
  end

  def create
    @pledge = Pledge.new pledge_params

    if @pledge.save
      redirect_to pledge_path(@pledge)
    else
      render :new
    end
  end

  def show
    @pledge = Pledge.find params[:id]
  end

  private
    def pledge_params
      params.require(:pledge).permit([:name, :email, :pledge])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charities/index.html.erb
<h1>Our Charities</h1>
<div id="charities">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('shared.learn_pledge_challenge') %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=1473549476242712&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="jumbotron">
      <h1><%= t('shared.learn_pledge_challenge') %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/learn.html.erb
<div class="row">
  <div class="col-md-6">
    <style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; height: auto; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/79771046' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
  </div>
  <div class="col-md-6">
    <h2><%= t('learn.watch_the_video') %></h2>
    <p><%= t('shared.lorem') %></p>
    <p><%= link_to t('shared.pledge'), new_pledge_path, class: 'btn btn-primary btn-lg', role: 'button' %></p>
  </div>
</div>

app/views/pledges/new.html.erb
<h2><%= t 'pledge.now_make_a_pledge' %></h2>

<div class="row">
  <div class="col-md-6">
    <%= simple_form_for @pledge do |f| %>
      <%= f.input :name, placeholder: 'Jane Micheals' %>
      <%= f.input :email, placeholder: 'jane.michaels@example.com' %>
      <%= f.input :pledge, placeholder: t('pledge.i_am_going_to_make_a_difference_by') %>
      <%= f.submit t('shared.pledge'), class: 'btn btn-success' %>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2><%= t 'pledge.suggestions' %></h2>
    <ul>
      <li><%= t 'pledge.suggestion_1' %></li>
      <li><%= t 'pledge.suggestion_2' %></li>
      <li><%= t 'pledge.suggestion_3' %></li>
      <li><%= t 'pledge.suggestion_4' %></li>
    </ul>
  </div>
</div>

app/views/pledges/show.html.erb
<div class="col-md-6">
  <h2>Debug</h2>
  <%= debug @pledge %>
  <div class="fb-share-button" data-href="<%= request.url %>"></div>
</div>